import { Area, AreaChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { formatMoney } from "../../../utils/currencyDisplay";

const COLORS = ["#123C91", "#12AFA0", "#7C3AED", "#D97706", "#DC2626"];
const labelOf = (value, interval) => { const date = new Date(value); return Number.isNaN(date.getTime()) ? String(value || "") : new Intl.DateTimeFormat("ar-EG", interval === "monthly" ? { month: "short", year: "numeric" } : { day: "numeric", month: "short" }).format(date); };

const EarningsTimelineChart = ({ points, interval, onIntervalChange }) => {
  const currencies = [...new Set(points.map((point) => point.currency))];
  const rows = [...points.reduce((map, point) => { const key = String(point.date || ""); const row = map.get(key) || { date: key }; row[point.currency] = point.amount; map.set(key, row); return map; }, new Map()).values()];
  return <div role="region" aria-labelledby="earnings-timeline-title" className="overflow-hidden rounded-2xl border border-[#E3E8EF] bg-white shadow-[0_4px_16px_rgba(16,24,40,0.04)]">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#EAECF0] px-4 py-4 sm:px-6 sm:py-5"><div><h2 id="earnings-timeline-title" className="text-base font-bold text-[#1F2937] sm:text-lg">تطور الأرباح</h2><p className="mt-1 text-xs text-[#667085] sm:text-sm">كل عملة تظهر في مسار مستقل للحفاظ على دقة الأرقام</p></div><div className="flex rounded-xl bg-[#F2F4F7] p-1" aria-label="الفترة الزمنية">{[{ value: "daily", label: "يومي" }, { value: "monthly", label: "شهري" }].map((item) => <button key={item.value} type="button" onClick={() => onIntervalChange(item.value)} aria-pressed={interval === item.value} className={`min-w-18 rounded-lg px-4 py-2 text-xs font-semibold transition ${interval === item.value ? "bg-white text-[#123C91] shadow-sm" : "text-[#667085] hover:text-[#344054]"}`}>{item.label}</button>)}</div></div>
    {!rows.length ? <div className="grid h-72 place-items-center px-4 text-center text-sm text-[#667085]">لا توجد بيانات أرباح للفترة المحددة.</div> : <div className="h-76 w-full px-1 py-4 sm:h-90 sm:px-4 sm:py-5" dir="ltr" role="img" aria-label={`مخطط الأرباح ${interval === "daily" ? "اليومية" : "الشهرية"}`}><ResponsiveContainer width="100%" height="100%"><AreaChart data={rows} margin={{ top: 8, right: 12, left: 0, bottom: 4 }}><CartesianGrid vertical={false} strokeDasharray="4 4" stroke="#EAECF0" /><XAxis dataKey="date" tickFormatter={(value) => labelOf(value, interval)} tick={{ fontSize: 11, fill: "#667085" }} axisLine={{ stroke: "#D0D5DD" }} tickLine={false} /><YAxis tick={{ fontSize: 11, fill: "#667085" }} axisLine={false} tickLine={false} width={55} /><Tooltip cursor={{ stroke: "#98A2B3", strokeDasharray: "4 4" }} contentStyle={{ borderRadius: 12, borderColor: "#EAECF0", boxShadow: "0 8px 20px rgba(16,24,40,.08)" }} labelFormatter={(value) => labelOf(value, interval)} formatter={(value, currency) => [formatMoney(value, currency), currency]} /><Legend iconType="circle" wrapperStyle={{ paddingTop: 12, fontSize: 12 }} />{currencies.map((currency, index) => <Area key={currency} type="monotone" dataKey={currency} connectNulls={false} stroke={COLORS[index % COLORS.length]} fill={COLORS[index % COLORS.length]} fillOpacity={0.08} strokeWidth={2.5} activeDot={{ r: 5 }} />)}</AreaChart></ResponsiveContainer></div>}
  </div>;
};
export default EarningsTimelineChart;
