import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import toast from "react-hot-toast";
import AdminLayout from "../../../components/admin/layout/AdminLayout";
import Breadcrumbs from "../../shared/Breadcrumbs";
import { getAvailableClassrooms, getSubscriptionRenewOptions, renewSubscription } from "../../../services/APIService";
import { adminApiErrorMessage, apiList, buildRenewalPayload, idOf, nameOf } from "../../../utils/adminSubscription";

const cls="h-10 w-full rounded-xl border border-gray-200 bg-white px-3 outline-none focus:border-[#123C91]";
const Detail=({label,value})=><div className="rounded-xl bg-gray-50 p-3"><span className="block text-xs text-gray-500">{label}</span><b className="mt-1 block text-sm">{value??"—"}</b></div>;
export default function RenewSubscriptionPage(){
 const {id}=useParams(),nav=useNavigate();
 const [data,setData]=useState(null),[items,setItems]=useState([]),[rooms,setRooms]=useState({}),[busy,setBusy]=useState(false),[warning,setWarning]=useState(null);
 useEffect(()=>{getSubscriptionRenewOptions(id).then(r=>{const d=r.data?.data||r.data;setData(d);setItems((d.items||[]).map(x=>({subject:idOf(x.subject),package:idOf(x.currentPackage),teacher:idOf(x.teacher),classroom:idOf(x.classroom),type:x.type||"group",discount:x.currentDiscount||0,_source:x}))) }).catch(e=>toast.error(adminApiErrorMessage(e,"تعذر تحميل خيارات التجديد")))},[id]);
 const update=(index,key,value)=>setItems(current=>current.map((x,i)=>i===index?{...x,[key]:value,...(["teacher","type"].includes(key)?{classroom:""}:{})}:x));
 useEffect(()=>{items.forEach((x,index)=>{if(!x.subject||!x.teacher||!x.type)return;getAvailableClassrooms({subject:x.subject,teacher:x.teacher,type:x.type}).then(r=>setRooms(old=>({...old,[index]:apiList(r,["classrooms","results","items"]).filter(c=>!c.status||c.status==="active")}))).catch(()=>{})})},[items]);
 const send=async confirmed=>{if(items.some(x=>![x.subject,x.package,x.teacher,x.classroom,x.type].every(Boolean)))return toast.error("يرجى استكمال كل خيارات التجديد");setBusy(true);try{const response=await renewSubscription(id,buildRenewalPayload(items,confirmed));const renewed=response.data?.data||response.data;const renewedId=idOf(renewed?.subscription)||idOf(renewed);toast.success("تم تجديد الاشتراك بنجاح");nav(renewedId?`/admin/subscriptions/${renewedId}`:"/admin/subscription",{replace:true})}catch(e){const body=e.response?.data;if(e.response?.status===409&&(body?.code||body?.message)==="ACTIVE_SUBSCRIPTION_HAS_REMAINING_SESSIONS")setWarning(body.details||{});else toast.error(adminApiErrorMessage(e,"تعذر تجديد الاشتراك"))}finally{setBusy(false)}};
 if(!data)return <AdminLayout><Breadcrumbs homeTo="/admin-dashboard"/><div dir="rtl" className="p-16 text-center text-gray-500">جاري تحميل خيارات التجديد...</div></AdminLayout>;
 return <AdminLayout><Breadcrumbs homeTo="/admin-dashboard"/><main dir="rtl" className="p-3 sm:p-6 font-['IBM_Plex_Sans_Arabic']"><h1 className="text-xl font-semibold text-[#123C91]">تجديد الاشتراك يدويًا</h1><div className="mt-4 grid gap-3 sm:grid-cols-2"><Detail label="الطالب" value={nameOf(data.student)}/><Detail label="حالة الاشتراك الحالي" value={data.subscription?.status}/></div>
 <div className="mt-5 space-y-4">{items.map((item,index)=>{const s=item._source,teachers=s.availableTeachers||data.teachers||[],packages=s.availablePackages||[];return <section key={s.id||index} className="rounded-2xl border bg-white p-5"><h2 className="font-bold text-[#123C91]">{nameOf(s.subject)}</h2><div className="mt-3 grid gap-3 sm:grid-cols-3"><Detail label="الباقة الحالية" value={nameOf(s.currentPackage)}/><Detail label="إجمالي الجلسات" value={s.totalSessions}/><Detail label="الجلسات المستخدمة" value={s.usedSessions}/><Detail label="الجلسات المتبقية" value={s.remainingSessions}/><Detail label="المعلم الحالي" value={nameOf(s.teacher)}/><Detail label="المجموعة الحالية" value={nameOf(s.classroom)}/></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
 <select aria-label="الباقة" className={cls} value={item.package} onChange={e=>update(index,"package",e.target.value)}>{packages.map(x=><option key={idOf(x)} value={idOf(x)}>{nameOf(x)}</option>)}</select>
 <select aria-label="المعلم" className={cls} value={item.teacher} onChange={e=>update(index,"teacher",e.target.value)}>{(teachers.length?teachers:[s.teacher]).map(x=><option key={idOf(x)} value={idOf(x)}>{nameOf(x)}</option>)}</select>
 <select aria-label="المجموعة" className={cls} value={item.classroom} onChange={e=>update(index,"classroom",e.target.value)}>{([s.classroom,...(rooms[index]||[])]).filter((x,i,a)=>idOf(x)&&a.findIndex(y=>idOf(y)===idOf(x))===i).map(x=><option key={idOf(x)} value={idOf(x)}>{nameOf(x)}</option>)}</select>
 <select aria-label="النوع" className={cls} value={item.type} onChange={e=>update(index,"type",e.target.value)}><option value="group">مجموعة</option><option value="private">فردي</option></select><input aria-label="الخصم" className={cls} type="number" min="0" value={item.discount} onChange={e=>update(index,"discount",e.target.value)}/>
 </div></section>})}</div><div className="mt-5 flex gap-3"><button disabled={busy} onClick={()=>send(false)} className="rounded-xl bg-[#123C91] px-6 py-2.5 text-white disabled:opacity-50">{busy?"جاري التجديد...":"تجديد الاشتراك"}</button><button onClick={()=>nav(-1)} className="rounded-xl border px-5">إلغاء</button></div>
 {warning&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/40 p-4"><div className="max-w-md rounded-2xl bg-white p-6 shadow-xl"><h2 className="text-lg font-bold text-red-700">تأكيد استبدال الاشتراك</h2><p className="mt-3 text-sm leading-7 text-gray-700">لا يزال بهذا الاشتراك {warning.totalRemainingSessions??"عدة"} جلسات متبقية. سيؤدي التجديد الآن إلى إنهاء الاشتراك الحالي، ولن تُنقل الجلسات المتبقية إلى الاشتراك الجديد.</p>{warning.items?.length>0&&<ul className="mt-2 list-inside list-disc text-sm text-gray-600">{warning.items.map((x,i)=><li key={x.subjectSubscriptionId||i}>{x.remainingSessions} جلسات متبقية</li>)}</ul>}<div className="mt-5 flex gap-3"><button disabled={busy} onClick={()=>send(true)} className="rounded-xl bg-red-600 px-5 py-2.5 text-white">تجديد رغم ذلك</button><button onClick={()=>setWarning(null)} className="rounded-xl border px-5">إلغاء</button></div></div></div>}
 </main></AdminLayout>
}
