import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import AdminLayout from "../../../components/admin/layout/AdminLayout";
import { approveAdminInstructorWithdrawal, confirmPaidAdminInstructorWithdrawal, getAdminInstructorWithdrawals, rejectAdminInstructorWithdrawal } from "../../../services/APIService";
import { getApiErrorMessage } from "../../../services/apiError";
const unwrap=r=>r?.data?.data??r?.data??r;
export default function AdminWithdrawalsPage(){const [items,setItems]=useState([]),[status,setStatus]=useState(""),[page,setPage]=useState(1),[pagination,setPagination]=useState({}),[working,setWorking]=useState(""),[action,setAction]=useState(null),[detail,setDetail]=useState("");
 const load=async()=>{try{const data=unwrap(await getAdminInstructorWithdrawals({status:status||undefined,page,limit:20}));setItems(Array.isArray(data)?data:data?.items||data?.withdrawals||[]);setPagination(data?.pagination||{});}catch(e){toast.error(getApiErrorMessage(e,"تعذر تحميل طلبات السحب"));}};
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{load();},[status,page]); // eslint-disable-line react-hooks/exhaustive-deps
 const act=async()=>{const {item,kind}=action||{},id=item?.id||item?._id;if(!id||working)return;if(kind!=="approve"&&!detail.trim())return toast.error("أدخل البيانات المطلوبة");const payload=kind==="approve"?(detail?{estimatedTransferHours:Number(detail)}:{}):kind==="reject"?{rejectionReason:detail.trim()}:{confirm:true,paymentMethod:"bank-transfer",externalReference:detail.trim()};setWorking(id);try{if(kind==="approve")await approveAdminInstructorWithdrawal(id,payload);if(kind==="reject")await rejectAdminInstructorWithdrawal(id,payload);if(kind==="paid")await confirmPaidAdminInstructorWithdrawal(id,payload);toast.success("تم تحديث الطلب");setAction(null);setDetail("");await load();}catch(e){toast.error(getApiErrorMessage(e,"تعذر تحديث الطلب"));}finally{setWorking("");}};
 return <AdminLayout><main dir="rtl" className="space-y-5 p-6"><div><h1 className="text-xl font-extrabold">طلبات سحب أرباح المحاضرين</h1><p className="text-sm text-gray-500">المعاملات المعروضة لا تتضمن بيانات دفع خاصة غير لازمة.</p></div>{action&&<div className="rounded-xl border bg-white p-4"><b>{action.kind==="approve"?"المهلة المتوقعة بالساعات (اختياري)":action.kind==="reject"?"سبب الرفض":"مرجع الدفع"}</b><div className="mt-2 flex gap-2"><input value={detail} onChange={e=>setDetail(e.target.value)} className="flex-1 rounded-lg border p-2"/><button onClick={act} disabled={Boolean(working)} className="rounded-lg bg-[#123C91] px-4 text-white">تأكيد</button><button onClick={()=>setAction(null)}>إلغاء</button></div></div>}<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}} className="rounded-lg border p-2"><option value="">كل الحالات</option>{["requested","approved","rejected","paid"].map(x=><option key={x}>{x}</option>)}</select><div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[760px] text-sm"><thead className="bg-gray-50"><tr><th className="p-3">المحاضر</th><th>المبلغ</th><th>الحالة</th><th>التاريخ</th><th>الإجراءات</th></tr></thead><tbody>{items.map(item=><tr key={item.id||item._id} className="border-t"><td className="p-3">{item.instructor?.fullName||item.instructor?.name||"—"}</td><td>{(Number(item.requestedAmountMinor)/10**Number(item.currencyScale??2)).toLocaleString("ar-EG")} {item.currency}</td><td>{item.status}</td><td>{new Date(item.requestedAt||item.createdAt).toLocaleString("ar-EG")}</td><td className="space-x-2 p-3 space-x-reverse">{item.status==="requested"&&<><button onClick={()=>{setAction({item,kind:"approve"});setDetail("");}} className="text-emerald-700">موافقة</button><button onClick={()=>{setAction({item,kind:"reject"});setDetail("");}} className="text-red-700">رفض</button></>}{item.status==="approved"&&<button onClick={()=>{setAction({item,kind:"paid"});setDetail("");}} className="text-[#123C91]">تأكيد الدفع</button>}{!["requested","approved"].includes(item.status)&&<span>للقراءة فقط</span>}</td></tr>)}</tbody></table></div><div className="flex justify-between"><button disabled={page<=1} onClick={()=>setPage(x=>x-1)}>السابق</button><span>{page} / {pagination.totalPages||1}</span><button disabled={page>=Number(pagination.totalPages||1)} onClick={()=>setPage(x=>x+1)}>التالي</button></div></main></AdminLayout>}
