import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { LoaderCircle, Scale } from "lucide-react";
import AdminLayout from "../../../components/admin/layout/AdminLayout";
import Breadcrumbs from "../../shared/Breadcrumbs";
import { getCourseMarketplaceConfig, getCurrentPolicy } from "../../../services/APIService";
import { getApiErrorMessage } from "../../../services/apiError";
const unwrap = (response) => response?.data?.data ?? response?.data ?? response;
export default function CommissionSettingsPage() {
  const [config, setConfig] = useState(null), [agreement, setAgreement] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState("");
  useEffect(() => { Promise.all([getCourseMarketplaceConfig(), getCurrentPolicy("revenue_share_agreement").catch(() => null)]).then(([rate, policy]) => { setConfig(unwrap(rate)); setAgreement(policy ? unwrap(policy) : null); }).catch((requestError) => setError(getApiErrorMessage(requestError, "تعذر تحميل العمولة المعتمدة"))).finally(() => setLoading(false)); }, []);
  return <AdminLayout><Breadcrumbs homeTo="/admin-dashboard" items={[{ label: "مالية الدورات", to: "/admin/course-finances" }, { label: "العمولة المعتمدة" }]} /><main dir="rtl" className="space-y-5 p-6 font-['IBM_Plex_Sans_Arabic']"><div><h1 className="text-xl font-bold">عمولة سوق الدورات</h1><p className="mt-1 text-sm text-gray-500">عرض للتهيئة التشغيلية المعتمدة التي يستخدمها الخادم عند إنشاء لقطة الشراء.</p></div>{loading ? <LoaderCircle className="animate-spin"/> : error ? <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div> : config ? <section className="grid gap-4 sm:grid-cols-2"><Rate label="عمولة المنصة" value={config.platformCommissionPercentage}/><Rate label="حصة المحاضر" value={config.instructorSharePercentage}/></section> : <div className="rounded-xl border p-4">القيمة المعتمدة غير متاحة حاليًا.</div>}<section className="rounded-2xl border bg-white p-5"><div className="flex items-start gap-3"><Scale className="text-[#123C91]"/><div><h2 className="font-bold">اتفاقية مشاركة الإيرادات</h2><p className="mt-1 text-sm text-gray-500">{agreement ? `النسخة المنشورة الحالية: ${agreement.version}` : "لا توجد نسخة منشورة متاحة."}</p><p className="mt-2 text-xs text-gray-500">تغيير التهيئة التشغيلية ليس متاحًا من هذه الشاشة في V1.</p><Link to="/admin/course-policies?type=revenue_share_agreement" className="mt-4 inline-block rounded-lg bg-[#123C91] px-4 py-2 text-sm font-bold text-white">إدارة الاتفاقية</Link></div></div></section></main></AdminLayout>;
}
function Rate({ label, value }) { return <div className="rounded-2xl border bg-white p-6"><p className="text-sm text-gray-500">{label}</p><p className="mt-2 text-4xl font-extrabold text-[#123C91]">{Number.isFinite(Number(value)) ? `${value}%` : "—"}</p></div>; }
