import { useEffect, useState } from "react";
import { X } from "lucide-react";
import StarRating from "./StarRating";

export default function CourseReviewFormModal({ open, review, submitting, apiError, onClose, onSubmit }) {
  const [rating, setRating] = useState(review?.rating || 0);
  const [reviewText, setReviewText] = useState(review?.reviewText || "");
  const [errors, setErrors] = useState({});
  useEffect(() => { if (!open) return undefined; const keydown = (event) => { if (event.key === "Escape" && !submitting) onClose(); }; window.addEventListener("keydown", keydown); return () => window.removeEventListener("keydown", keydown); }, [open, submitting, onClose]);
  if (!open) return null;
  const submit = (event) => { event.preventDefault(); const next = {}; if (!Number.isInteger(rating) || rating < 1 || rating > 5) next.rating = "اختر تقييماً من نجمة إلى خمس نجوم."; if (reviewText.length > 2000) next.reviewText = "الحد الأقصى 2000 حرف."; setErrors(next); if (!Object.keys(next).length) onSubmit({ rating, reviewText: reviewText.trim() || null }, setErrors); };
  return <div className="fixed inset-0 z-[140] grid place-items-center bg-black/60 p-3" onMouseDown={(event) => event.target === event.currentTarget && !submitting && onClose()}><form role="dialog" aria-modal="true" aria-labelledby="review-form-title" onSubmit={submit} className="max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-5 text-right shadow-2xl"><div className="flex items-center justify-between"><h2 id="review-form-title" className="text-lg font-extrabold">{review ? "تعديل تقييمك" : "أضف تقييمك"}</h2><button type="button" disabled={submitting} onClick={onClose} aria-label="إغلاق" className="rounded-lg p-2 hover:bg-gray-100 disabled:opacity-50"><X size={19} /></button></div><div className="mt-5"><span className="mb-2 block text-sm font-bold">التقييم</span><StarRating value={rating} onChange={setRating} size={28} disabled={submitting} />{errors.rating && <p className="mt-1 text-xs text-red-600">{errors.rating}</p>}</div><label className="mt-5 block text-sm font-bold">رأيك (اختياري)<textarea value={reviewText} maxLength={2000} disabled={submitting} onChange={(event) => { setReviewText(event.target.value); setErrors((current) => ({ ...current, reviewText: undefined })); }} rows={6} className="mt-2 w-full resize-y rounded-xl border border-[#D0D5DD] p-3 font-normal leading-7 focus:border-[#123C91]" placeholder="شارك تجربتك مع الدورة..." /></label><div className="flex justify-between text-xs"><span className="text-red-600">{errors.reviewText || (apiError?.field === "reviewText" ? apiError.message : "")}</span><span className="text-[#98A2B3]" dir="ltr">{reviewText.length}/2000</span></div>{apiError?.message && apiError?.field !== "reviewText" && <p className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{apiError.message}</p>}<div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" disabled={submitting} onClick={onClose} className="rounded-lg border px-5 py-2.5 disabled:opacity-50">إلغاء</button><button type="submit" disabled={submitting} className="rounded-lg bg-[#123C91] px-5 py-2.5 font-bold text-white disabled:opacity-60">{submitting ? "جاري الحفظ..." : review ? "حفظ التعديلات" : "نشر التقييم"}</button></div></form></div>;
}
