import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import AdminLayout from "../../components/admin/layout/AdminLayout";
import { POLICY_LABELS } from "../../components/course/PolicyAcceptanceDialog";
import { createAdminPolicyDraft, getAdminPolicyVersions, publishAdminPolicy, updateAdminPolicyDraft } from "../../services/APIService";
import { getApiErrorMessage } from "../../services/apiError";
const TYPES=Object.keys(POLICY_LABELS), unwrap=r=>r?.data?.data??r?.data??r, blank={title:{ar:"",en:""},content:{ar:"",en:""},effectiveAt:"",criteria:[],platformCommissionBps:""};
export default function AdminPoliciesPage(){
 const queryType=new URLSearchParams(location.search).get("type"),[type,setType]=useState(TYPES.includes(queryType)?queryType:TYPES[0]),[versions,setVersions]=useState([]),[selected,setSelected]=useState(null),[form,setForm]=useState(blank),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);try{const data=unwrap(await getAdminPolicyVersions({type})),list=Array.isArray(data)?data:data?.items||data?.versions||[];setVersions(list);setSelected(list[0]||null);setForm(list[0]||blank);}catch(e){toast.error(getApiErrorMessage(e,"تعذر تحميل السياسات"));}finally{setLoading(false);}};
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{load();},[type]); // eslint-disable-line react-hooks/exhaustive-deps
 const local=(field,lang,value)=>setForm(x=>({...x,[field]:{...(x[field]||{}),[lang]:value}}));
 const payload=()=>({title:form.title,content:form.content,...(form.effectiveAt?{effectiveAt:new Date(form.effectiveAt).toISOString()}:{}),...(type==="course_publishing_policy"?{criteria:form.criteria}:{}),...(type==="revenue_share_agreement"?{platformCommissionBps:Number(form.platformCommissionBps)}:{})});
 const save=async()=>{setSaving(true);try{selected?.status==="draft"?await updateAdminPolicyDraft(selected.id||selected._id,payload()):await createAdminPolicyDraft(type,payload());toast.success("تم حفظ المسودة");await load();}catch(e){toast.error(getApiErrorMessage(e,"تعذر حفظ المسودة"));}finally{setSaving(false);}};
 const publish=async()=>{setSaving(true);try{await publishAdminPolicy(selected.id||selected._id);toast.success("تم نشر النسخة");await load();}catch(e){toast.error(getApiErrorMessage(e,"تعذر نشر النسخة"));}finally{setSaving(false);}};
 const readonly=selected&&selected.status!=="draft";
 return <AdminLayout><main dir="rtl" className="space-y-5 p-6"><h1 className="text-xl font-extrabold">السياسات والاتفاقيات</h1><div className="flex gap-2 overflow-x-auto">{TYPES.map(x=><button key={x} onClick={()=>setType(x)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-sm font-bold ${x===type?"bg-[#123C91] text-white":"border bg-white"}`}>{POLICY_LABELS[x]}</button>)}</div>{loading?<p>جاري التحميل...</p>:<div className="grid gap-5 lg:grid-cols-[240px_1fr]"><aside className="space-y-2 rounded-xl border bg-white p-3"><button onClick={()=>{setSelected(null);setForm(blank);}} className="w-full rounded-lg bg-blue-50 p-3 font-bold text-[#123C91]">+ مسودة جديدة</button>{versions.map(v=><button key={v.id||v._id} onClick={()=>{setSelected(v);setForm(v);}} className="w-full rounded-lg border p-3 text-right text-sm"><b>نسخة {v.version||"مسودة"}</b><span className="block text-xs text-gray-500">{v.status}</span></button>)}</aside><section className="space-y-4 rounded-xl border bg-white p-5"><div className="grid gap-3 sm:grid-cols-2">{["ar","en"].map(lang=><div key={lang} className="space-y-2"><input disabled={readonly} value={form.title?.[lang]||""} onChange={e=>local("title",lang,e.target.value)} placeholder={`العنوان ${lang}`} className="w-full rounded-lg border p-3"/><textarea disabled={readonly} value={form.content?.[lang]||""} onChange={e=>local("content",lang,e.target.value)} placeholder={`المحتوى ${lang}`} rows="12" className="w-full rounded-lg border p-3" dir={lang==="ar"?"rtl":"ltr"}/></div>)}</div><input disabled={readonly} type="datetime-local" value={form.effectiveAt?String(form.effectiveAt).slice(0,16):""} onChange={e=>setForm({...form,effectiveAt:e.target.value})} className="rounded-lg border p-3"/>{type==="revenue_share_agreement"&&<input disabled={readonly} type="number" value={form.platformCommissionBps??""} onChange={e=>setForm({...form,platformCommissionBps:e.target.value})} placeholder="عمولة المنصة بنقاط الأساس" className="w-full rounded-lg border p-3"/>}{type==="course_publishing_policy"&&<Criteria value={form.criteria||[]} disabled={readonly} onChange={criteria=>setForm({...form,criteria})}/>} {!readonly&&<div className="flex gap-2"><button disabled={saving} onClick={save} className="rounded-lg bg-[#123C91] px-5 py-3 font-bold text-white">حفظ المسودة</button>{selected?.status==="draft"&&<button disabled={saving} onClick={publish} className="rounded-lg bg-emerald-600 px-5 py-3 font-bold text-white">نشر النسخة</button>}</div>}</section></div>}</main></AdminLayout>;
}
function Criteria({value,onChange,disabled}){const update=(i,patch)=>onChange(value.map((x,j)=>j===i?{...x,...patch}:x));return <div className="space-y-2"><b>معايير جودة النشر</b>{value.map((c,i)=><div key={i} className="grid gap-2 rounded-lg border p-3 sm:grid-cols-2"><input disabled={disabled} value={c.key||""} placeholder="key" onChange={e=>update(i,{key:e.target.value})}/><input disabled={disabled} value={c.title?.ar||""} placeholder="العنوان العربي" onChange={e=>update(i,{title:{...c.title,ar:e.target.value}})}/><textarea disabled={disabled} value={c.description?.ar||""} placeholder="الوصف العربي" onChange={e=>update(i,{description:{...c.description,ar:e.target.value}})}/><label><input disabled={disabled} type="checkbox" checked={c.required!==false} onChange={e=>update(i,{required:e.target.checked})}/> إلزامي</label></div>)}{!disabled&&<button onClick={()=>onChange([...value,{key:"",title:{ar:"",en:""},description:{ar:"",en:""},required:true,sortOrder:value.length}])} className="text-[#123C91]">+ إضافة معيار</button>}</div>}
